name: Build, tests

# When to trigger this workflow
on:
  push:
  pull_request:
    branches: [ master, feature ]

jobs:
  hello-world:
    name: "Build"
    # Runner node
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: egor-tensin/setup-gcc@v1
    - name: "Install armadillo lib"
      run: |
        sudo apt-get --yes install libarmadillo-dev
    - name: "Build Step 1"
      run: |
        echo "Starting make"
        make

